INSTALL_PREFIX=${PWD}/install
EXTRA_CMAKE_FLAGS=-DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
		-DPYTHON_BINDINGS=ON \
		-DBUILD_MODELS=ON \
		-DCMAKE_PREFIX_PATH=`rospack find eigen`\
		-DCMAKE_BUILD_TYPE="Release"\
		-DPYTHON_SITE_PACKAGES_DIR=${INSTALL_PREFIX}/lib/python/site-packages\
		-DENABLE_TESTS=ON

default: all
	cd build; make install


include $(shell rospack find mk)/cmake.mk

