<?xml version="1.0"?>
<?xml-model
  href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>orocos_kdl</name>
  <version>1.5.4</version>
  <description>
    This package contains a recent version of the Kinematics and Dynamics
    Library (KDL), distributed by the Orocos Project.
  </description>
  <maintainer email="MatthijsBurgh@outlook.com">Matthijs van der Burgh</maintainer>
  <url type="website">https://www.orocos.org/kdl</url>
  <url type="repository">https://github.com/orocos/orocos_kinematics_dynamics</url>
  <url type="bugtracker">https://github.com/orocos/orocos_kinematics_dynamics/issues</url>
  <license>LGPL-2.1-or-later</license>

  <author>Ruben Smits</author>
  <author>Erwin Aertbelien</author>
  <author>Orocos Developers</author>
  <author email="MatthijsBurgh@outlook.com">Matthijs van der Burgh</author>

  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>
  <build_depend>eigen</build_depend>

  <exec_depend>eigen</exec_depend>
  <exec_depend>pkg-config</exec_depend>

  <test_depend>cppunit</test_depend>

  <doc_depend>doxygen</doc_depend>
  <doc_depend>graphviz</doc_depend>
  <doc_depend>python3-sphinx</doc_depend>

  <export>
    <build_type>cmake</build_type>
    <rosdoc2>rosdoc2.yaml</rosdoc2>
  </export>

</package>
