FIND_PATH(BOOST boost/numeric/ublas/matrix.hpp  )
IF ( BOOST )
    MESSAGE(STATUS "-- Looking for Boost Ublas - found")
    SET(KDL_CFLAGS "${KDL_CFLAGS} -I${BOOST}" CACHE INTERNAL "")
ELSE ( BOOST )
    MESSAGE(FATAL "-- Looking for Boost Ublas - not found")
ENDIF ( BOOST )