module KDL {
module Corba {
        typedef sequence<double> DoubleSequence;
                struct vector {
                        double x;
                        double y;
                        double z;
                };
                struct rotation {
                        double Xx;
                        double Xy;
                        double Xz;
                        double Yx;
                        double Yy;
                        double Yz;
                        double Zx;
                        double Zy;
                        double Zz;
                };
                struct frame {
                        vector p;
                        rotation M;
                };
                struct wrench {
                        vector force;
                        vector torque;
                };
                struct twist {
                        vector vel;
                        vector rot;
                };

};
};
